### ISSUE TITLE
Update KeyStore to use Path than string

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/johnnycanencrypt#148]
Right now we are using strings to store the `KeyStore` database path. We should instead use `pathlib.Path` everywhere. This will also help for the tests on Windows.

**Comment by euri10** [comment]
I came to the  same conclusion looking at your PR @kushaldas , which I expanded on ( see below), solved almost all issues but a rather big and annoying one on th db upgrade, it fails on renaming the file with a PermissionError
I ended up giving up because I dont have windows and debugging in the CI was rather not fun

https://github.com/euri10/johnnycanencrypt/tree/tests_on_windows

**Comment by kushaldas** [comment]
> I ended up giving up because I dont have windows and debugging in the CI was rather not fun

I can understand the pain :) I am focusing on all the other things to clean up first. And then I will look into Windows update. One step at a time.
I may do a few more PRs before I go back to windows land. We will know soon :D
